name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  camas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
      - run: nix develop --command camas
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: evidence-matrix
          path: build/matrix/
  zephyr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          path: cerive
      - uses: actions/setup-python@v7.0.0
        with:
          python-version: "3.12"
      - uses: zephyrproject-rtos/action-zephyr-setup@v1.0.15
        with:
          app-path: cerive
          manifest-file-name: zephyr/west.yaml
          toolchains: arm-zephyr-eabi
      - run: west twister -T cerive/tests/zephyr -p qemu_cortex_m3 --inline-logs -v
      - run: grep -r "SUITE PASS - 100.00% \[cerive\]" twister-out
