name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  camas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
      - run: nix develop --command camas
